config_version : 0

name: translated_hello_world

# This project is deliberately not versioned as 'major.minor.patch' to illustrate that this
# versioning scheme has no special meaning to res - you can use whatever versioning scheme
# makes sense for your particular package.
version: 5

uuid: cb7f6a02-f165-11e0-8e05-0023ae79d988

authors:
- dave.mccormack
- matthew.strong
- glenn.thompson

description: >
 A simple C++ executable that links to another library.

variants:
- [ !OS!, !CXX! ]

requires:
- translate_lib-2.0

tools:
- test_translated_hello_world

commands:
- export PATH=$PATH:!ROOT!/bin
