config_version : 0

version : 11.0.701

variants:
- [ Linux ]

requires:
- boost-1.37.0
- python-2.5

help:
- [ "general", "firefox http://www.sidefx.com/docs/houdini11.0" ]
- [ "hdk", "firefox http://www.sidefx.com/docs/hdk11.0/main.html" ]


commands:
- export HFS=!ROOT!/ext
- export HOUDINI_VERSION=11.0.701
- export HOUDINI_MAJOR_RELEASE=11
- export HOUDINI_MINOR_RELEASE=0
- export TEMP=/Local/tmp
- export HOUDINI_TEMP_DIR=$TEMP
# prepend ld_lib_path so that hou-boost libs appear before boost native libs
- export LD_LIBRARY_PATH=!ROOT!/ext/dsolib:$LD_LIBRARY_PATH
- export PATH=$PATH:!ROOT!/ext/bin
- export HDSO=!ROOT!/ext/dsolib
- export HT=!ROOT!/ext/toolkit
- export HIS=!ROOT!/ext/houdini
- export HH=!ROOT!/ext/houdini
- export CMAKE_MODULE_PATH=$CMAKE_MODULE_PATH:!ROOT!/cmake
- export HOUDINI_OTLSCAN_PATH='&':@/otls/Chop:@/otls/Cop2:@/otls/Dop:@/otls/Driver:@/otls/Object:@/otls/Shop:@/otls/Sop:@/otls/Vop:@/otls/Pop:$HOUDINI_OTLSCAN_PATH
- export HOUDINI_SCRIPT_PATH='&':$HOUDINI_SCRIPT_PATH
- export HOUDINI_UI_ICON_PATH='&':$HOUDINI_UI_ICON_PATH
- export HOUDINI_DSO_PATH='&':$HOUDINI_DSO_PATH
- export HOUDINI_PATH='&':$HOUDINI_PATH
- export HOUDINI_SOHO_PATH='&':$HOUDINI_SOHO_PATH
- export SESI_LMHOST=houdinilic01
