config_version : 0

version : 6.3.2

variants :
- [ Linux ]

requires:
- python-2.5

commands:
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:!ROOT!/ext
- export CMAKE_MODULE_PATH=$CMAKE_MODULE_PATH:!ROOT!/cmake
- export PATH=$PATH:!ROOT!/ext/bin
- export NUKE_TEMP_DIR=/Local/tmp/nuke_temp
- export NUKE_DDImageVersion=6.3v2
- export FOUNDRY_LICENSE_FILE=27000@nukelic01.drd.int
- export LM_LICENSE_FILE=27000@nukelic01.drd.int # farm related stuff
