image:
- Visual Studio 2015  # for Python 2.7
- Ubuntu

install:
  - echo I run on both..
  - ps: echo ..Windows..
  - sh: echo ..and Linux!

  # Try setup.py
  - pip install --user .

  # Then try install.py
  - python install.py -v ./install

test_script:
  - sh: echo $(pwd)
  - ps: echo %cd%
  - sh: export PATH=/home/appveyor/projects/bleeding-rez/install/bin:$PATH
  - ps: set PATH=C:\projects\bleeding-rez\install\Scripts;%PATH%
  - rez --version
  - rez env -- exit
  - rez memcache
  - rez-memcache
  - rez bind --quickstart

build: off
