---
image:
  - Visual Studio 2015  # for Python 2.7
  - Ubuntu

# Enable build_script below
build: Script

environment:
  PYPI_LOGIN: mottosso

  # Encrypt @ https://ci.appveyor.com/account/mottosso/tools/encrypt
  PYPI_PASSWORD:
    secure: O34+lDNbRNVJ2EgaHAmEVg==

build_script:
  - cmd: pip install .
  - sh: sudo pip install .

test_script:
  - rez --version
  - rez env -- exit
  - rez bind --quickstart

  # Skip CMake tests on Windows, they don't work
  - cmd: cmake --version
  - cmd: del "C:\Program Files (x86)\CMake\bin\cmake.exe"

  # Run selftest
  - cmd: rez selftest -s cmd -vvv
  - sh: rez selftest -s bash -vvv

  # Coverage
  - sh: sudo pip install coverage codecov
  - sh: coverage run -m rez selftest -s bash
  - sh: codecov


#
# Automatically upload to PyPI whenever a new tag is made
#
deploy_script:
  - cmd: python .appveyor/deploy.py