image:
- Visual Studio 2015  # for Python 2.7
- Ubuntu

install:
  - echo I run on both..
  - ps: echo ..Windows..
  - sh: echo ..and Linux!

  # Try setup.py
  - pip install --user .

  # Then try install.py
  - python install.py -v ./install

test_script:
  - sh: export PATH=$(pwd)/install/bin
  - ps: set PATH=%cd%\install\Scripts
  - rez --version
  - rez env -- exit
  - rez memcache
  - rez-memcache
  - rez bind --quickstart

build: off
