image:
- Visual Studio 2015  # for Python 2.7
- Ubuntu

install:
  - I run on both..
  - ps: ..Windows..
  - sh: ..and Linux!

  # Try setup.py
  - pip install . --user

  # Then try install.py
  - python install.py -v ./install

test_script:
  - rez --version
  - rez env -- exit
  - rez memcache
  - rez-memcache
  - rez bind --quickstart

build: off