[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.mypy]
python_version = "3.8"
files = ["src/rez/", "src/rezplugins/"]
exclude = [
    '.*/rez/data/.*',
    '.*/rez/vendor/.*',
    '.*/rez/tests/.*',
    '.*/rez/utils/lint_helper.py',
]
disable_error_code = ["var-annotated", "import-not-found"]
check_untyped_defs = true
# allow this for now:
allow_redefinition = true
follow_imports = "silent"

[[tool.mypy.overrides]]
module = 'rez.utils.lint_helper'
follow_imports = "skip"

[[tool.mypy.overrides]]
module = "rez.version._version"
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = "rez.version._requirement"
disallow_untyped_defs = true
