config_version : 0

name: toupper

version: 1.0.0

uuid: 147f0b62-f87e-11e0-aa91-0023ae79d988

authors:
- allan.johns

description: >
 Simple project to illustrate use of a custom build package.

build_requires:
- buildTools_toupper-3.1

commands:
- export PATH=$PATH:!ROOT!/bin


