#!/bin/bash

. _set-rez-env

#
# If run from the working copy of a git repo, this utility will
# print out all git commit messages that have occurred since the last
# released tag.
#

rev_url=`rez-git-print-last-tag`
result=$?

if [ $result -eq 2 ]; then
	exit 1
elif [ $result -eq 3 ]; then
	echo "Changelog since first branch commit:(NONE)"
	git log | cat
	exit 0
elif [ $result -eq 4 ]; then
	exit 1
elif [ $result -ne 0 ]; then
	echo "Changelog since first revision, tag:(NONE)"
	git log | cat
	exit 0
fi

rev=`echo $rev_url | awk '{print $1}'`
url=`echo $rev_url | awk '{print $2}'`

echo "Changelog since tag: "$rev
git log $rev.. | cat

#    Copyright 2012 BlackGinger Pty Ltd (Cape Town, South Africa)
#
#    Copyright 2008-2012 Dr D Studios Pty Limited (ACN 127 184 954) (Dr. D Studios)
#
#    This file is part of Rez.
#
#    Rez is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Rez is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with Rez.  If not, see <http://www.gnu.org/licenses/>.
