#!/bin/bash

#
# If run from the working copy of an svn checkout, this utility will
# print the current svn url. If not, it will print "(NONE)". In either
# case the non-error code zero is returned.
#
# TODO remove this, put into rez-build


svndir=`( svn info | grep '^URL' ) 2> /dev/null`
if [ $? -ne 0 ]; then
	echo "(NONE)"
	exit 0
fi

echo $svndir | awk '{print $NF}'

#    Copyright 2008-2012 Dr D Studios Pty Limited (ACN 127 184 954) (Dr. D Studios)
#
#    This file is part of Rez.
#
#    Rez is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Rez is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with Rez.  If not, see <http://www.gnu.org/licenses/>.
