config_version : 0

name: hello_world_cpp

version: 3.4.0

uuid: 7abf7e48-f0b3-11e0-b332-0023ae79d988

authors:
- joe.bloggs
- charlie.sheen

description: >
 The simplest C++ example package, it's a single executable.

variants:
- [ !OS!, !CXX! ]

tools:
- test_hello_world_cpp

commands:
- export PATH=$PATH:!ROOT!/bin

