#!/usr/bin/env python
import os
import sys
import argparse



def _add_common_args(subp):
    subp.add_argument("--no-del-tmpdir", dest="no_del_tmpdir", action="store_true",
                      help=argparse.SUPPRESS)


if __name__ == '__main__':
    p = argparse.ArgumentParser(
        description='Rez command-line tool',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    subps = p.add_subparsers(dest="cmd")
    subparsers = {}

    def _add_subcommand(cmd, help):
        subp = subps.add_parser(cmd, help=help)
        _add_common_args(subp)
        # TODO is this slowing down rez startup time? Try moving all parser setup into this file
        # TODO to avoid importing all the cli sourcefiles.
        exec("from rez.cli.%s import setup_parser" % cmd.replace('-','_'))
        setup_parser(subp)
        subparsers[cmd] = subp

    _add_subcommand("context-info",
                    "Print information about the current shell.")
    _add_subcommand("settings",
                    "Print current rez settings.")
    _add_subcommand("env",
                    "Open a rez-configured shell, possibly interactive.")

    opts = p.parse_args()
    cmd = opts.cmd
    exec("from rez.cli.%s import command" % cmd.replace('-','_'))
    returncode = command(opts, subparsers[cmd])

    if not opts.no_del_tmpdir:
        from rez.util import clean_tmpdir
        clean_tmpdir()

    sys.exit(returncode or 0)
