#!/usr/bin/env python
import os
import argparse



def _add_common_args(subp):
    pass


if __name__ == '__main__':
    p = argparse.ArgumentParser(
        description='Rez command-line tool',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    subps = p.add_subparsers(dest="cmd")
    subparsers = {}

    def _add_subcommand(cmd, help):
        subp = subps.add_parser(cmd, help=help)
        _add_common_args(subp)
        exec("from rez.cli.%s import setup_parser" % cmd.replace('-','_'))
        setup_parser(subp)
        subparsers[cmd] = subp

    _add_subcommand("context-info",
                    "Print information about the current shell.")
    _add_subcommand("settings",
                    "Print current rez settings.")
    _add_subcommand("env",
                    "Open a rez-configured shell, possibly interactive.")

    opts = p.parse_args()
    cmd = opts.cmd
    exec("from rez.cli.%s import command" % cmd.replace('-','_'))
    command(opts, subparsers[cmd])
    from rez.util import clean_tmpdir
    #clean_tmpdir()
