config_version : 0

name: %(NAME)s

version: %(VERSION)s

uuid: %(UUID)s

authors:
- %(USER)s

description: >
 Enter description here. Multiline is ok, but make sure that you 
 leave the single leading space on each line, as shown here.

%(REQUIRES)s

%(VARIANTS)s

%(BUILD_REQUIRES)s

%(HELP)s

%(TOOLS)s

%(COMMANDS)s
