name: Setup python

description: Setup python using either actions/setup-pythono or conda

inputs:
  python-version:
    description: Python version to setup
    required: true
  os:
    description: os
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }} with actions/setup-python
      if: ${{ inputs.python-version != '2.7' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Python ${{ inputs.python-version }} with conda
      if: ${{ inputs.python-version == '2.7' }}
      shell: bash
      run: |
        cd /tmp
        if [[ "${{ inputs.os }}" = macos* ]]; then
            curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o /tmp/miniconda.sh
        else
            curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o /tmp/miniconda.sh
        fi

        case "${{ inputs.os }}" in
            macos*)
                curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o /tmp/miniconda.sh
                sh /tmp/miniconda.sh -b -p /opt/conda
                ;;
            ubuntu*)
                curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
                sh /tmp/miniconda.sh -b -p /opt/conda
                ;;
            windows*)
                curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -o /c/miniconda.sh
                sh /tmp/miniconda.sh -b -p /c/conda
                ;;
        esac

    - name: Create conda environment
      if: ${{ inputs.python-version == '2.7' }}
      shell: bash
      run: |
        if [[ "${OSTYPE}" == "msys" ]]; then
            eval "$(/c/conda/condabin/conda.bat shell.bash hook)"
        else
            source /opt/conda/bin/activate
        fi
        conda create -n python python=2.7 setuptools wheel

    - name: Fix conda installed python
      if: inputs.python-version == '2.7' && (startsWith(inputs.os, 'ubuntu') || startsWith(inputs.os, 'macos'))
      shell: bash -el {0}
      run: |
        set -ex

        source /opt/conda/bin/activate
        conda activate python
        conda info

        if [[ "${{ inputs.os }}" = macos* ]]; then
            install_name_tool -change @rpath/libpython2.7.dylib $(dirname $(which python))/../lib/libpython2.7.dylib $(which python)
        else
            sudo apt-get install patchelf

            # This will allow virtualenv to work correctly.
            # Basically, Python provided by conda is "fully portable". Its default
            # RPATH is "$ORIGIN/../lib". The problem is that once the virtualenv
            # is created, the copied/symlinked interpreter in the venv won't be
            # able to load lib since the lib folder isn't copied in the venv.
            patchelf --set-rpath $(dirname $(which python))/../lib $(which python)
        fi
