config_version : 0

name: hello_world_py

version: 1.0.0

uuid: cb555d96-f09f-11e0-aca9-0023ae79d988

authors:
- joe.bloggs

description: >
 The simplest python example package.

requires:
- python-!PYVER!

tools:
- test_hello_world_py

commands:
- export PYTHONPATH=$PYTHONPATH:!ROOT!/py
- export PATH=$PATH:!ROOT!/bin


