config_version : 0

name: my_wrappers

version: 3.2

uuid: ea49b214-bbdb-11df-a452-002564afd011

authors:
- serj.tankian

description: >
 Example wrapper.

commands:
- export PATH=$PATH:!ROOT!
- export REZ_WRAPPER_PATH=$REZ_WRAPPER_PATH:!ROOT!
