name = "simple_meson"

version = "1.0.0"

authors = ["meson"]

description = "A project generated by `meson init`."

uuid = "9a2eeb8b-26bc-4fe8-9c4b-faeddf075c1f"

tools = ["simple"]

def commands() -> None:
    env.PATH.append("{root}/bin")
