complete rez 'C/*/`_rez_completion`/'
complete rezolve 'C/*/`_rez_completion`/'
complete rez-env 'C/*/`_rez_completion`/'
complete rez-search 'C/*/`_rez_completion`/'
complete rez-view 'C/*/`_rez_completion`/'
complete rez-help 'C/*/`_rez_completion`/'
complete rez-config 'C/*/`_rez_completion`/'
