name: wheel
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  launchers:
    name: launcher
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Build
      run: |
        git clone https://github.com/pypa/distlib.git
        cp launcher/CMakeLists.txt distlib/PC/
        cd distlib/PC
        # $devenv=(Split-Path -Path (vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1))
        # $env:PATH="$devenv;$env:PATH"
        # echo $env:PATH
        # echo $devenv
        # ls
        # msbuild SimpleLauncher.sln -p:Configuration=Release -p:Platform=x64

        # $vsInstallation = (vswhere -products * 17.0 -property installationPath)
        # echo $vsInstallation
        # VC\\Auxiliary\\Build\\vcvarsall.bat<
        # $env:VERBOSE=1

        cmake . -GNinja
        cmake --build .

        ls
