#
# Picks up docker image from hub.docker.com as repository.
#
# Requires a DOCKERHUB_TOKEN secret and username/repository to match the github
# repository. For example: nerdvegas/rez -> User/Repository: nerdvegas
#
# Uses image tagged as **latest** commit revision of any file within:
#  .github/docker/windows/**
#  .github/workflows/windows-docker-image.yaml
#

name: Windows Docker

on:
  # Do not run if Docker image has been updated
  pull_request:
    paths-ignore:
      - '.github/docker/**'
      - '.github/workflows/windows-docker-image.yaml'
  push:
    paths-ignore:
      - '.github/docker/**'
      - '.github/workflows/windows-docker-image.yaml'

jobs:
  main:
    runs-on: windows-2019

    strategy:
      matrix:
        # Needs to match python version of images (see windows-docker-image.yaml)
        python-version:
          - '2.7.17'
          - '3.6.8'
          - '3.7.5'
      fail-fast: false

    steps:
    - name: Login to docker repository
      run: |
        ${gh_user} = ("${{ github.repository }}" -Split '/')[0]
        docker login -u ${gh_user} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v1
    - name: Pull docker image
      run: |
        ${gh_user} = ("${{ github.repository }}" -Split '/')[0]
        ${Env:LAST_DOCKER_REVISION} = $( git log -n 1 --author-date-order --pretty=format:%H -- .\.github\docker\rez-win-py\  .\.github\workflows\windows-docker-image.yaml ).SubString(0, 8)
        echo "Pulling rez-win-py:${{ matrix.python-version }}-${Env:LAST_DOCKER_REVISION}"
        docker pull ${gh_user}/rez-win-py:${{ matrix.python-version }}-${Env:LAST_DOCKER_REVISION}

    - name: Run the Docker image
      run: |
        ${gh_user} = ("${{ github.repository }}" -Split '/')[0]
        ${Env:LAST_DOCKER_REVISION} = $( git log -n 1 --author-date-order --pretty=format:%H -- .\.github\docker\rez-win-py\  .\.github\workflows\windows-docker-image.yaml ).SubString(0, 8)
        docker run ${gh_user}/rez-win-py:${{ matrix.python-version }}-${Env:LAST_DOCKER_REVISION} ${{ github.repository }} ${{ github.sha }}
